inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-rock: defaults.yml

inherit_mode:
  merge:
  - Exclude
  - AllowedNames

AllCops:
  TargetRubyVersion: "2.5"

Style/MultilineMemoization:
    EnforcedStyle: braces

Naming/MethodParameterName:
  AllowedNames:
  - as
  - m
  - kw
  - x
  - y

Metrics/AbcSize:
  Max: 17

Style/ClassAndModuleChildren:
  Enabled: false